"""empty message

Revision ID: 6d003ad779f6
Revises: 8cab96550846
Create Date: 2024-09-10 16:32:23.968894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d003ad779f6'
down_revision = '8cab96550846'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.Integer(), nullable=False))
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=70),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_items_category'), ['category'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_items_category'))
        batch_op.alter_column('gender',
               existing_type=sa.String(length=70),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('category')

    # ### end Alembic commands ###
